### ISSUE TITLE
Can't get no-asm to compile on Ubuntu 14.04 x86_64

### ISSUE THREAD

**Issue by mczero80** [Ericson2314/Voxlap#25]
So far this fork seems like the best approach to get voxlap to compile on all systems.

But when I run make, I get those errors:

g++ -o binaries/simple.elf.o -funsigned-char -m32 -mfpmath=sse -msse -m3dnow -ffast-math -ggdb -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-unused-but-set-variable `sdl-config --cflags` -D USEV5ASM=1 -I ./include -c source/simple.cpp
In file included from source/simple.cpp:17:0:
./include/voxlap5.h:129:2: error: a storage class on an anonymous aggregate in class scope is not allowed
  static union { point3d s, x; }; //kv6data.xsiz direction in VXL coordinates
  ^
./include/voxlap5.h:130:2: error: a storage class on an anonymous aggregate in class scope is not allowed
  static union
  ^
./include/voxlap5.h:135:2: error: a storage class on an anonymous aggregate in class scope is not allowed
  static union { point3d h, y; }; //kv6data.ysiz direction in VXL coordinates
  ^
./include/voxlap5.h:137:2: error: a storage class on an anonymous aggregate in class scope is not allowed
  static union { point3d f, z; }; //kv6data.zsiz direction in VXL coordinates
  ^
In file included from source/simple.cpp:26:0:
./include/porthacks.h:67:12: warning: ‘int memcasecmp(const void_, const void_, size_t)’ defined but not used [-Wunused-function]
 static int memcasecmp (const void \* const ptr0, const void \* const ptr1, size_t n)
            ^
make: **\* [binaries/simple.elf.o] Fehler 1

Ideas? Thanks :)

**Comment by aponigricon** [comment]
This is an old, abandoned project which is no longer maintained. You are welcome to try continuing it in a separate fork, but you should know that although Voxlap is a beautiful piece of software, it is currently severely obsolete and you wouldn't achieve much even if you managed to finish this port.
If you really want to go ahead though, the one person who knows everything you need to know is definitely @Ericson2314, who was the primary (and in practice only) maintainer back when this repository was still active.

**Comment by Ericson2314** [comment]
Well, it would have been helpful if my constant force-pushing didn't make collaboration near impossible :).

Yeah this fork is sooo dead. and Vlad is right that even if you do get it to work, its probably not what you were looking for. If I do ever return for this, it will mainly be because sentimentality.

The storage class stuff has to do with those anonymous structs and unions being globals, not type defs. Try building with various `--std=XXX` combinations, it is possible g++'s defaults have gotten more restrictive since I last touched this.
